/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Hw10 */

#ifndef _Included_Hw10
#define _Included_Hw10
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Hw10
 * Method:    round_up
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Hw10_round_1up
  (JNIEnv *, jclass, jint);

/*
 * Class:     Hw10
 * Method:    convertFtoC
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_Hw10_convertFtoC
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
