
Hw10 : Hw10.java temp_convert.c
	javac Hw10.java
	gcc -shared -fpic -ansi -Wall -o libtconv.so -I/usr/lib/jvm/java-7-openjdk-amd64/include/ \
	    -I/usr/lib/jvm/java-7-openjdk-amd64/include/ temp_convert.c
